### ISSUE TITLE
Reading and writing FATfs

### ISSUE THREAD

**Issue by Prathik4** [everslick/piratos#1]
Hello, first of all you have done some great work.
I'm working on a academic project were I'm using freertos and I want to write data to FATfs (either sd card itself or USB storage), while running 6-DOF(six degree of freedom) control's code.
So i was wondering if was possible with piratos. Since in 'src' their is 'fs' folder which I think handles Filesystem. If it is possible can you give me a hint or example on how to use it.
Thank you in advance. 👍

**Comment by everslick** [comment]
sorry, this project is not functional at all, ATM. if github would let me hide a repository, this would be great, because then it would not waste anybodys time. but i'm not ready to give up on it completely either. ;-) one day i will start work on it again.

there are some bare metal projects that do something similar though. you will have to look around.

sorry that i can't be more helpful.

**Comment by Prathik4** [comment]
It's ok and thanks for the reply.. 👍
